### ISSUE TITLE
Contracts are not stored with IB gateway

### ISSUE THREAD

**Issue by danhdoan** [vnpy/vnpy#2419]
* OS: Windows 10
* vn.py: v2.1.1 branch master

## Issue
Bug

I'm using VNPY 2.1.1 with IB demo account. I can perform order/trade (currently on IDEALPRO) on IB and it works well but I cannot perform Contract Query (see 2nd image). 
When I trace code (on `ib_gateway.py`), I found that the handler `process_contract_event ` has never been called, so no contracts are saved on vnpy environment.
Besides, when I trade, `name` of stocks are not shown (see 1st image)

Please see the images below for more details:
![2020-04-08](https://user-images.githubusercontent.com/12591333/78850584-6bf92200-79cc-11ea-9b9d-6b3ba6412435.png)
![2020-04-08 (1)](https://user-images.githubusercontent.com/12591333/78850586-6dc2e580-79cc-11ea-9249-278411e33655.png)

Thanks in advance!

**Comment by vnpy** [comment]
Hi,

Due to the too many trading contracts provided by IB, IB API does not provide any function to query all contracts (or even contracts of a certain exchange). Instead, there is only a function (reqContractDetails) to query the detail of a contract one by one.

In vn.py, this reqContractDetails function is called when you subscribe the tick data. So you have to subscribe a tick data first, and then you can see the contract detail in that Contract Inquiry dialog.

After the contract data is received, it will be stored in a local json file. So the next time you connect IB gateway, you should be able to see it in Contract Inquiry without doing the tick subscription.

**Comment by danhdoan** [comment]
Thanks for answering my question. It works now.
