### ISSUE TITLE
[enhancement] add dynamic leverage rate for margin, future gateways

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#2452]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Can you add dynamic leverage rate for margin, future gateways ?
Recently, vnpy only supported fix leverage (max multiple) which bring max risk for strategy. 
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
In vn.py, we use cross margin (CME futures margin mode) instead of isolated margin (OTC forex margin mode), so the only factor which influences your risk level should be your total position value, or  in another word, how many contracts you open. Therefore, there is no need to change leverage level, but using the max multiple is enought.
