### ISSUE TITLE
Could not find the Qt platform plugin "cocoa" in ""

### ISSUE THREAD

**Issue by bobingxin** [vnpy/vnpy#3400]
## 环境

* 操作系统: mac m1 13.0.1
* Python版本: Python 3.9.13
* VeighNa版本: 如v3.6.0发行版

## Issue类型
三选一：Question

## 重现步骤
bash install_osx.sh
cd examples/veighna_trader
python run.py

针对Bug类型Issue，请提供具体重现步骤以及报错截图
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by vnpy** [comment]
请安装下Python 3.10后，再尝试看看。

**Comment by mago960806** [comment]
@vnpy 
类似的Issues，但可以排除操作系统的影响，应该和Python版本或者PyQT6有关。
## 环境
- 操作系统: Windows11
- Python版本: 3.10.10
- VeighNa版本: 3.6.0
## 报错信息
PS D:\vnpy> python .\examples\veighna_trader\run.py
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
## 重现步骤
python .\examples\veighna_trader\run.py
